### ISSUE TITLE
CvPcb not showing up the global libraries

### ISSUE THREAD

**Issue by sitilge** [KiCad/Connectors_JST.pretty#21]
Hi there,

First, thank you for the great tool. Is there a reason why the libraries added with wizard in CvPcb are not showing up in global tab? I managed to get them working by using setting them as project specific.

Permissions, probably?

**Comment by evanshultz** [comment]
@sitilge 

Sorry that no one answered you. Can you please share more about what you mean? I don't find any issues using the latest released KiCad, 4.0.6, but perhaps I don't understand. If you can provide more details we'll try to resolve your issue.

**Comment by sitilge** [comment]
@evanshultz if only I could remember... Will investigate the issue once again.
