### ISSUE TITLE
JST_PH_B*B-PH-SM4 start at pin 0

### ISSUE THREAD

**Issue by rglenn** [KiCad/Connectors_JST.pretty#37]
The JST_PH_B*B-PH-SM4 footprints start at pin 0. This was done in commit d6af4a1a7f2d9d39f81ed10fc1ab7754dc30fb1e, but doesn't match the datasheet or the through-hole version of the connector.

Was this intentional, or a mistake? I don't see anything in KLC that would require this.

Thanks!

**Comment by SchrodingersGat** [comment]
@poeschlr it appears that some of your PH scripts have pin zero as the first pin. Can you please resubmit ALL PH connectors with pin-1 as "1" ? If you can just change the initial pin number I'll make sure this gets merged ASAP.

Thanks for raising this issue @rglenn sorry that it wasn't caught previously.

**Comment by poeschlr** [comment]
Looks like only the smd version is affected. I will fix my scripts and create a pull request within the next hour or so.

**Comment by SchrodingersGat** [comment]
Fixed in https://github.com/KiCad/Connectors_JST.pretty/pull/38

**Comment by rglenn** [comment]
Thanks!
