### ISSUE TITLE
Drill sizes for XH and EH connectors are a bit small

### ISSUE THREAD

**Issue by poeschlr** [KiCad/Connectors_JST.pretty#40]
I noticed that the drill size for the XH and EH series is a bit on the small side.
In the datasheet it is given as 0.9 +0.1/-0.0mm (yes zero in negative direction.)
As i stated in my pull request https://github.com/KiCad/Connectors_JST.pretty/pull/39 i had recently problems with a board. (That's the reason why i noticed that in the datasheet the negative tolerance is given as zero.)

I also noticed that for the XH 2 pin variants the drill size should be 1+/-0.05mm.
This means in my opinion it would be good to change the footprints such that the 2 pin variant has a 1mm drill and all others a 0.95mm drill.

@SchrodingersGat these footprints are generated with your scripts. (They use the pad array which is not yet merged into the repository by @pointhi.) I could merge your repo into my fork and fix the issues with the footprints if you don't have time for that. (Or i could rewrite the scripts such that they work under the current footprint generator. Whatever you prefer.)

**Comment by poeschlr** [comment]
ZE and PUD Connectors have the same problem.
There the drill is given as 0.7 +0.1/-0.0 in the datasheet. In the footprint it currently is 0.7mm.

Only the J2100 series has an adequate drill size. There it is given in the datasheet as 0.85 +0.05/-0.03mm and in the footprint 0.9mm is used. (so the drill size in this footprints is actually on the large side.)

**Comment by SchrodingersGat** [comment]
Thanks for finding this - I will make some adjustments to my scripts.

**Comment by SchrodingersGat** [comment]
PR here - https://github.com/KiCad/Connectors_JST.pretty/pull/42
