### ISSUE TITLE
Error while loading footprints

### ISSUE THREAD

**Issue by ThomasGravekamp** [KiCad/Connectors_JST.pretty#44]
When loading the library I get the following error:
> PARSE_ERROR: Onafgebroken gescheiden string in input/source
> this repo -> JST_PUD_S08B-PUDSS-1_2x04x2.00mm_Angled.kicad_mod

Which roughly translates into:
> PARSE_ERROR: Unterminated string in input/source
> this repo -> JST_PUD_S08B-PUDSS-1_2x04x2.00mm_Angled.kicad_mod

This is introduced in merge commit Merge pull request #42 from SchrodingersGat/drill-size-fix (e8e216bd988e5a357c90882e940856ac11e83662).

`- (pad "" np_thru_hole...`
`+ (pad " np_thru_hole...`

Multiple files in the merge commit seem to contain this error.

**Comment by SchrodingersGat** [comment]
Thomas,

Thanks for letting us know, fixed [here](https://github.com/KiCad/Connectors_JST.pretty/pull/45)

**Comment by SchrodingersGat** [comment]
Let me know if this has addressed the issue :)

**Comment by ThomasGravekamp** [comment]
Yep, it has been fixed. Thanks.
